<?php

namespace Database\Seeders;

use App\Models\CameraPreset;
use App\Models\FilmRoll;
use App\Models\SubscriptionPlan;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        // Admin User
        $admin = User::firstOrCreate(
            ['email' => 'admin@example.com'],
            [
                'name' => 'Admin User',
                'password' => bcrypt('password'),
                'role' => 'admin',
                'email_verified_at' => now(),
            ]
        );

        // Test Customer User
        $user = User::firstOrCreate(
            ['email' => 'test@example.com'],
            [
                'name' => 'Test User',
                'password' => bcrypt('password'),
                'role' => 'user',
                'email_verified_at' => now(),
            ]
        );

        // Mobile Camera Profiles & Presets
        $presets = [
            [
                'preset_key' => 'classic_35',
                'name' => 'Classic 35',
                'engine' => 'film_v1',
                'version' => 1,
                'lut' => 'cameras/portra-400.cube',
                'lut_intensity' => 0.90,
                'grain' => 0.35,
                'bloom' => 0.15,
                'vignette' => 0.25,
                'softness' => 0.05,
                'date_stamp' => true,
                'aspect_ratio' => '4:3',
                'is_premium' => false,
                'minimum_app_version' => '0.1.0',
                'description' => 'Iconic 35mm rangefinder tone with natural warmth and rich earthy tones.',
                'is_active' => true,
            ],
            [
                'preset_key' => 'summer_35',
                'name' => 'Summer 35',
                'engine' => 'film_v1',
                'version' => 1,
                'lut' => 'cameras/summer-35.cube',
                'lut_intensity' => 0.85,
                'grain' => 0.30,
                'bloom' => 0.20,
                'vignette' => 0.15,
                'softness' => 0.10,
                'date_stamp' => false,
                'aspect_ratio' => '4:3',
                'is_premium' => false,
                'minimum_app_version' => '0.1.0',
                'description' => 'Bright summer tones with warm crimson highlights and soft grain.',
                'is_active' => true,
            ],
            [
                'preset_key' => 'kodak_gold_200',
                'name' => 'Kodak Gold 200',
                'engine' => 'film_v1',
                'version' => 1,
                'lut' => 'cameras/kodak-gold-200.cube',
                'lut_intensity' => 0.90,
                'grain' => 0.40,
                'bloom' => 0.18,
                'vignette' => 0.20,
                'softness' => 0.05,
                'date_stamp' => true,
                'aspect_ratio' => '4:3',
                'is_premium' => false,
                'minimum_app_version' => '0.1.0',
                'description' => 'Golden luxury nostalgia with sun-drenched warmth and timeless skin tones.',
                'is_active' => true,
            ],
            [
                'preset_key' => 'ccd_pop',
                'name' => 'CCD Pop',
                'engine' => 'film_v1',
                'version' => 1,
                'lut' => 'cameras/superia-400.cube',
                'lut_intensity' => 0.85,
                'grain' => 0.10,
                'bloom' => 0.12,
                'vignette' => 0.15,
                'softness' => 0.00,
                'date_stamp' => true,
                'aspect_ratio' => '4:3',
                'is_premium' => false,
                'minimum_app_version' => '0.1.0',
                'description' => 'Nostalgic early 2000s silver digicam punch with vibrant color boost.',
                'is_active' => true,
            ],
            [
                'preset_key' => 'sakura_mini',
                'name' => 'Sakura Mini',
                'engine' => 'film_v1',
                'version' => 1,
                'lut' => 'cameras/sakura-mini.cube',
                'lut_intensity' => 0.88,
                'grain' => 0.25,
                'bloom' => 0.35,
                'vignette' => 0.18,
                'softness' => 0.12,
                'date_stamp' => false,
                'aspect_ratio' => '1:1',
                'is_premium' => true,
                'minimum_app_version' => '0.1.0',
                'description' => 'Pastel pink dreamy instant film with soft blooming highlights and light leaks.',
                'is_active' => true,
            ],
            [
                'preset_key' => 'disposable_90',
                'name' => 'Disposable 90',
                'engine' => 'film_v1',
                'version' => 1,
                'lut' => 'cameras/cinestill-800t.cube',
                'lut_intensity' => 0.95,
                'grain' => 0.45,
                'bloom' => 0.25,
                'vignette' => 0.30,
                'softness' => 0.08,
                'date_stamp' => true,
                'aspect_ratio' => '4:3',
                'is_premium' => false,
                'minimum_app_version' => '0.1.0',
                'description' => '90s party flash disposable camera with warm nostalgia and flash pop.',
                'is_active' => true,
            ],
            [
                'preset_key' => 'rolleiflex_tlr',
                'name' => 'Rolleiflex TLR 75',
                'engine' => 'film_v1',
                'version' => 1,
                'lut' => 'cameras/rolleiflex-tlr.cube',
                'lut_intensity' => 0.90,
                'grain' => 0.40,
                'bloom' => 0.15,
                'vignette' => 0.40,
                'softness' => 0.10,
                'date_stamp' => false,
                'aspect_ratio' => '1:1',
                'is_premium' => true,
                'minimum_app_version' => '0.1.0',
                'description' => 'Twin-Lens Reflex medium format 6x6 square depth with circular vintage vignetting.',
                'is_active' => true,
            ],
            [
                'preset_key' => 'polaroid_sx70',
                'name' => 'Polaroid SX-70',
                'engine' => 'film_v1',
                'version' => 1,
                'lut' => 'cameras/polaroid-sx70.cube',
                'lut_intensity' => 0.92,
                'grain' => 0.35,
                'bloom' => 0.20,
                'vignette' => 0.35,
                'softness' => 0.10,
                'date_stamp' => false,
                'aspect_ratio' => '1:1',
                'is_premium' => false,
                'minimum_app_version' => '0.1.0',
                'description' => '1970s iconic square instant Polaroid look with cyan-shifted shadows & warm highlights.',
                'is_active' => true,
            ],
            [
                'preset_key' => 'fnc_800',
                'name' => 'FNC Cam 800',
                'engine' => 'film_v1',
                'version' => 1,
                'lut' => 'cameras/midnight-tokyo.cube',
                'lut_intensity' => 0.90,
                'grain' => 0.45,
                'bloom' => 0.15,
                'vignette' => 0.35,
                'softness' => 0.05,
                'date_stamp' => true,
                'aspect_ratio' => '4:3',
                'is_premium' => false,
                'minimum_app_version' => '0.1.0',
                'description' => 'Industrial vintage teal function camera with ISO 800 film stock & custom tuning.',
                'is_active' => true,
            ],
            [
                'preset_key' => 'fuji_velvia_50',
                'name' => 'Fuji Velvia 50',
                'engine' => 'film_v1',
                'version' => 1,
                'lut' => 'cameras/fuji-velvia-50.cube',
                'lut_intensity' => 0.95,
                'grain' => 0.20,
                'bloom' => 0.10,
                'vignette' => 0.20,
                'softness' => 0.00,
                'date_stamp' => false,
                'aspect_ratio' => '3:2',
                'is_premium' => true,
                'minimum_app_version' => '0.1.0',
                'description' => 'Ultra-vivid landscape slide film with emerald greens and deep saturated skies.',
                'is_active' => true,
            ],
            [
                'preset_key' => 'mono_400',
                'name' => 'Mono 400',
                'engine' => 'film_v1',
                'version' => 1,
                'lut' => 'cameras/noir-800.cube',
                'lut_intensity' => 1.00,
                'grain' => 0.50,
                'bloom' => 0.05,
                'vignette' => 0.40,
                'softness' => 0.00,
                'date_stamp' => false,
                'aspect_ratio' => '4:3',
                'is_premium' => false,
                'minimum_app_version' => '0.1.0',
                'description' => 'High-contrast monochrome black and white film with rich silver tonal gradation.',
                'is_active' => true,
            ],
            [
                'preset_key' => 'super_8',
                'name' => 'Super 8 Movie',
                'engine' => 'film_v1',
                'version' => 1,
                'lut' => 'cameras/cine-noir-500.cube',
                'lut_intensity' => 0.90,
                'grain' => 0.60,
                'bloom' => 0.25,
                'vignette' => 0.45,
                'softness' => 0.15,
                'date_stamp' => true,
                'aspect_ratio' => '4:3',
                'is_premium' => true,
                'minimum_app_version' => '0.1.0',
                'description' => 'Vintage 8mm home cinema movie tone with edge vignetting and analog frame warmth.',
                'is_active' => true,
            ],
            [
                'preset_key' => 'vhs_1986',
                'name' => 'VHS 1986',
                'engine' => 'film_v1',
                'version' => 1,
                'lut' => 'cameras/vhs-1986.cube',
                'lut_intensity' => 0.90,
                'grain' => 0.45,
                'bloom' => 0.25,
                'vignette' => 0.30,
                'softness' => 0.10,
                'date_stamp' => true,
                'aspect_ratio' => '4:3',
                'is_premium' => false,
                'minimum_app_version' => '0.1.0',
                'description' => 'Retro 1980s magnetic camcorder look with chromatic tape color separation.',
                'is_active' => true,
            ],
            [
                'preset_key' => 'midnight_tokyo',
                'name' => 'Midnight Tokyo 3D',
                'engine' => 'film_v1',
                'version' => 1,
                'lut' => 'cameras/midnight-tokyo.cube',
                'lut_intensity' => 0.92,
                'grain' => 0.50,
                'bloom' => 0.30,
                'vignette' => 0.35,
                'softness' => 0.10,
                'date_stamp' => false,
                'aspect_ratio' => '16:9',
                'is_premium' => true,
                'minimum_app_version' => '0.1.0',
                'description' => 'Moody 3-lens cyber noir with deep midnight cyan shadows and neon glow.',
                'is_active' => true,
            ],
            [
                'preset_key' => 'cyber_neon',
                'name' => 'Cyber Neon 80s',
                'engine' => 'film_v1',
                'version' => 1,
                'lut' => 'cameras/cyber-neon.cube',
                'lut_intensity' => 0.95,
                'grain' => 0.35,
                'bloom' => 0.45,
                'vignette' => 0.35,
                'softness' => 0.08,
                'date_stamp' => true,
                'aspect_ratio' => '16:9',
                'is_premium' => true,
                'minimum_app_version' => '0.1.0',
                'description' => 'Synthwave vaporwave neon filter with glowing purple-magenta highlights.',
                'is_active' => true,
            ],
            [
                'preset_key' => 'safari_camp',
                'name' => 'Safari Camp 35',
                'engine' => 'film_v1',
                'version' => 1,
                'lut' => 'cameras/safari-camp.cube',
                'lut_intensity' => 0.90,
                'grain' => 0.40,
                'bloom' => 0.12,
                'vignette' => 0.30,
                'softness' => 0.05,
                'date_stamp' => true,
                'aspect_ratio' => '4:3',
                'is_premium' => false,
                'minimum_app_version' => '0.1.0',
                'description' => 'Rugged olive safari field camera with earthy greens and desert warmth.',
                'is_active' => true,
            ],
        ];

        foreach ($presets as $p) {
            CameraPreset::updateOrCreate(['preset_key' => $p['preset_key']], $p);
        }

        // Subscription Plans
        $plans = [
            [
                'name' => 'Free Starter',
                'slug' => 'free-starter',
                'price' => 0.00,
                'currency' => 'USD',
                'interval' => 'monthly',
                'max_rolls' => 3,
                'max_photos_per_roll' => 24,
                'allows_custom_presets' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Pro Photographer',
                'slug' => 'pro-photographer',
                'price' => 4.99,
                'currency' => 'USD',
                'interval' => 'monthly',
                'max_rolls' => 15,
                'max_photos_per_roll' => 36,
                'allows_custom_presets' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Unlimited Studio',
                'slug' => 'unlimited-studio',
                'price' => 9.99,
                'currency' => 'USD',
                'interval' => 'monthly',
                'max_rolls' => 999,
                'max_photos_per_roll' => 36,
                'allows_custom_presets' => true,
                'is_active' => true,
            ],
        ];

        foreach ($plans as $pl) {
            SubscriptionPlan::firstOrCreate(['slug' => $pl['slug']], $pl);
        }

        // Sample Film Roll
        $preset = CameraPreset::first();
        FilmRoll::firstOrCreate(
            ['invite_code' => 'TOKYO2026'],
            [
                'user_id' => $user->id,
                'title' => 'Tokyo Night Walk',
                'description' => 'Street photography around Shibuya and Shinjuku',
                'invite_code' => 'TOKYO2026',
                'max_photos' => 36,
                'current_photos' => 12,
                'roll_type' => 'standard',
                'status' => 'active',
                'camera_preset_id' => $preset?->id,
            ]
        );
    }
}
